---
apiVersion: v1
kind: Namespace
metadata:
  name: game-train
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-train
  name: deployment-train
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-train
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-train
    spec:
      containers:
      - image: chesky1/train-schedule
        imagePullPolicy: Always
        name: app-train
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-train
  name: service-train
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-train
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: game-train
  name: ingress-train
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-train
            port:
              number: 80
